version: "3"

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - app_data:/var/lib/postgresql/data/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    networks:
      - database_network
  
  grpc:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile
    
    env_file: .env

    restart: always
    volumes:
      - .:/app
    
    networks:
      - database_network
      - grpc_network
    ports:
      - 50051:50051
    depends_on:
      - db
    

networks:
  database_network:
  grpc_network:
volumes:
  app_data:
