version: "3"

services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - app_data:/var/lib/postgresql/data/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    networks:
      - database_network
  
  redis:
    hostname: redis
    image: redis:6-alpine
    networks:
      - redis_network
      - net_api
  
  
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASSWORD=guest
    ports:
      - "5673:5672"
    networks:
      - net_api
      - rabbit_network
  
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.develop

    restart: always
    volumes:
      - .:/app
    
    networks:
      - net_api
      - database_network
      - grpc_network
    ports:
      - 5000:5000
    depends_on:
      - db
  
  celery:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.celery
    restart: always    
    volumes: 
      - .:/app
    links: 
      - rabbit      
    depends_on: 
      - rabbit      
    networks:  
      - rabbit_network
      - redis_network
      - database_network
      - grpc_network
  
  # grpc:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/Dockerfile.grpc

  #   restart: always
  #   volumes:
  #     - .:/app
    
  #   networks:
  #     - net_api
  #     - database_network
  #     - grpc_network
  #   ports:
  #     - 50051:50051
  #   depends_on:
  #     - db
    

networks:
  net_api:
  database_network:
  rabbit_network:
  redis_network:
  grpc_network:
volumes:
  app_data:
