---
apiVersion: v1
kind: Service
metadata:
  name: grpc_server
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: grpc_server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc_server
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: grpc_server
  
  template:
    metadata:
      labels:
        app: grpc_server
    spec:
      imagePullSecrets:
        - name: staging-dh

      containers:
      - name: grpc_server
        image: registry.digitalocean.com/staging-dh/grpc_server-dev:${BUILD_NUMBER}
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: grpc_server
      
      - name: grpc_server-celery
        image: registry.digitalocean.com/staging-dh/grpc_server-dev:${BUILD_NUMBER}
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: grpc_server

      initContainers:
      - name: init-rabbit-vhost
        image: curlimages/curl:7.69.1
        command: ['curl']
        args: ['-u', '$(RABBITMQ_DEFAULT_USER):$(RABBITMQ_DEFAULT_PASS)', '-X', 'PUT', 'http://rabbitmq:15672/api/vhosts/$(DEPLOY_NAME)']
        envFrom:
        - configMapRef:
            name: rabbitmq
        env:
        - name: DEPLOY_NAME
          value: 'grpc_server'
      